### ISSUE TITLE
model adaptations, question

### ISSUE THREAD

**Issue by felix-salfelder** [dwarning/VA-Models#2]
The README states that models are "adapted" to specific implementations. I wonder what these adaptations are and if they could be made conditional for where they seem to be useful.

Some model generators hardwire preprocessor constants, such as `insideADMS, to protect non-ADMS users by making changes conditional on such constants.

Could this practice please be considered (or documented) for other backends as well? This will increase the usefulness of the endeavour, and will make changes easier to spot.

Greetings
felix

**Comment by dwarning** [comment]
There is a git development branch adms-xyce where I started XYCE specific adaptions. Perhaps Qucs can participate from that.
I am open to modify main branch so it can used in different simulators. Will Qucs stay at ADMS or switch to openVAF?
For me it is not easy to check the models in the different flavours of Qucs. I am failing mostly in the step of symbol generation and setup test benches.

**Comment by dwarning** [comment]
Even not answered by issue opener - closed.
