### ISSUE TITLE
openvaf compilation failures

### ISSUE THREAD

**Issue by stafverhaegen-chipflow** [dwarning/VA-Models#5]
I have several of the models that don't compile with openvaf due to the `__XYCE__` check present in the code. I am using latest openvaf version 23.5.0 downloaded precompiled from the website. I compile the modules using the `openvaf-compile-va.sh` script in the `code` directory.
Errors for `hicum2/vacode/hicumL2V3p0p0.va`:

```console
error: macro '`elsif' has not been declared
    --> /home/verhaegs/eda/code/VA-Models/code/hicum2/vacode/hicumL2V3p0p0.va:818:1
    |
818 | `elsif __XYCE__
    | ^^^^^^ macro not found here

error: unexpected token identifier; expected ';'
    --> /home/verhaegs/eda/code/VA-Models/code/hicum2/vacode/hicumL2V3p0p0.va:819:5
    |
818 | `elsif __XYCE__
    |                - expected ';'
819 |     Vbiei = $limit(V(br_biei),"typedpnjlim_new",VT,VT*ln(VT/(`M_SQRT2*ibeis_t)));
    |     ^^^^^ unexpected token

error: '__XYCE__' was not found in the current scope
    --> /home/verhaegs/eda/code/VA-Models/code/hicum2/vacode/hicumL2V3p0p0.va:818:8
    |
818 | `elsif __XYCE__
    |        ^^^^^^^^ not found

error: could not compile `hicumL2V3p0p0.va` due to 3 previous errors
```

This happens for the following models:

* `hicum2/vacode/hicumL2V3p0p0.va`
* `IGBT/vacode/nigbt.va`
* `mextram/505p2p0_vacode/bjt505.va`
* `mextram/505p2p0_vacode/bjt505t.va`
* `vbic/vacode/vbic_1p3.va`

I now compiled the code by commenting out the ``` `elsif __XYCE__``` sections.

**Comment by dwarning** [comment]
Please use the nightly version from [https://github.com/pascalkuthe/OpenVAF](url).
Your version will not work because of the elseif/elsif bug in openVAF. It is now fixed.

**Comment by stafverhaegen-chipflow** [comment]
Confirmed working with nightly version of openVAF
